name: Pikafish

on:
  push:
    branches:
      - master

jobs:
  Pikafish:
    name: ${{ matrix.config.name }}${{ matrix.arch }}
    runs-on: ${{ matrix.config.os }}
    env:
      ARCH: x86-64${{ matrix.arch }}
      COMPILER: clang++
      COMP: clang
      EXE: pikafish${{ matrix.arch }}${{ matrix.config.ext }}
    strategy:
      matrix:
        config:
          - name: Linux
            os: ubuntu-20.04 
            shell: bash {0}
          - name: MacOS
            os: macos-latest
            shell: bash {0}
          - name: Windows
            os: windows-latest
            shell: msys2 {0}
            ext: .exe
        arch: ["-vnni512", "-avx512", "-bmi2", "-avx2", "-modern", ""]
    defaults:
      run:
        working-directory: src
        shell: ${{ matrix.config.shell }}

    steps:
      - uses: actions/checkout@v3

      - name: Download required linux packages
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt upgrade clang llvm

      - name: Setup msys and install required packages
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: clang64
          install: mingw-w64-clang-x86_64-clang make git expect

      - name: Install unzip on msys
        if: runner.os == 'Windows'
        run: |
          pacman -S unzip --noconfirm
      
      - name: Download nnue weight for profile guided optimization build
        uses: robinraju/release-downloader@v1.7
        with:
          latest: true
          zipBall: true
          out-file-path: "nnue-weights"

      - name: Compile ${{ matrix.arch }} build
        run: |
          unzip $GITHUB_WORKSPACE/nnue-weights/Pikafish.*.zip pikafish.nnue
          make clean
          make -j profile-build EXE=$EXE
          make strip EXE=$EXE

      - name: Copy binary to folder
        run: |
          cd ..
          mkdir ${{ matrix.config.name }}
          cp src/$EXE ${{ matrix.config.name }}

      - name: Download wiki
        run: |
          git clone https://github.com/official-pikafish/Pikafish.wiki.git ../Wiki
          cd ../wiki
          rm -rf .git

      - uses: actions/upload-artifact@v3
        with:	
          name: Pikafish
          path: |
            ${{ matrix.config.name }}/*
            Wiki
            AUTHORS
            Copying.txt
            README.md
            Top CPU Contributors.txt

  Pikafish-Android:
    name: Android-${{ matrix.arch }}
    runs-on: ubuntu-latest
    env:
      ARCH: ${{ matrix.arch }}
      COMPILER: aarch64-linux-android21-clang++
      COMP: ndk
      EXE: pikafish-${{ matrix.arch }}
      LDFLAGS: "-static -Wno-unused-command-line-argument"
    strategy:
      matrix:
        arch: ["armv8-dotprod", "armv8"]
    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v3

      - name: Download required linux packages
        run: |
          sudo apt update
          sudo apt install qemu-user

      - name: Install NDK
        run: |
          NDKV="21.4.7075529"
          ANDROID_ROOT=/usr/local/lib/android
          ANDROID_SDK_ROOT=$ANDROID_ROOT/sdk
          SDKMANAGER=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager
          echo "y" | $SDKMANAGER "ndk;$NDKV"
          ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/$NDKV
          ANDROID_NDK_BIN=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin
          echo "ANDROID_NDK_BIN=$ANDROID_NDK_BIN" >> $GITHUB_ENV
 
      - name: Download nnue weight for profile guided optimization build
        uses: robinraju/release-downloader@v1.7
        with:
          latest: true
          zipBall: true
          out-file-path: "nnue-weights"

      - name: Compile ${{ matrix.arch }} build
        run: |
          export PATH=${{ env.ANDROID_NDK_BIN }}:$PATH
          unzip $GITHUB_WORKSPACE/nnue-weights/Pikafish.*.zip pikafish.nnue
          make clean
          make -j profile-build EXE=$EXE WINE_PATH=$EMU
          make strip EXE=$EXE

      - name: Copy binary to folder
        run: |
          cd ..
          mkdir Android
          cp src/$EXE Android

      - uses: actions/upload-artifact@v3
        with:	
          name: Pikafish	
          path: |
            Android/*
            AUTHORS
